# Generated by Django 6.0.3 on 2026-04-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start_date', models.DateField()),
                ('goal', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Plan repas',
                'verbose_name_plural': 'Plans repas',
            },
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Petit-déjeuner'), ('LUNCH', 'Déjeuner'), ('DINNER', 'Dîner'), ('SNACK', 'Snack')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Élément plan repas',
                'verbose_name_plural': 'Éléments plan repas',
            },
        ),
    ]
