# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mealprep', '0001_initial'),
        ('personnalisation', '0001_initial'),
        ('plats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealplanitem',
            name='custom_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personnalisation.customdish'),
        ),
        migrations.AddField(
            model_name='mealplanitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plats.dish'),
        ),
        migrations.AddField(
            model_name='mealplanitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mealprep.mealplan'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'week_start_date'], name='plan_user_week_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.UniqueConstraint(fields=('user', 'week_start_date'), name='uniq_user_week_plan'),
        ),
        migrations.AddIndex(
            model_name='mealplanitem',
            index=models.Index(fields=['plan', 'day'], name='mealplan_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealplanitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dish__isnull', False), ('custom_dish__isnull', True)), models.Q(('dish__isnull', True), ('custom_dish__isnull', False)), _connector='OR'), name='check_mealplanitem_xor_product'),
        ),
        migrations.AddConstraint(
            model_name='mealplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'day', 'meal_type'), name='uniq_plan_day_mealtype'),
        ),
    ]
