# Generated by Django 6.0.3 on 2026-04-08 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('calories', models.IntegerField()),
                ('proteines', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('payee', 'Payée'), ('preparee', 'Préparée'), ('livree', 'Livrée')], default='attente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('facture_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteine', models.CharField(choices=[('poulet', 'Poulet'), ('tofu', 'Tofu'), ('boeuf', 'Boeuf')], max_length=50)),
                ('legumes', models.CharField(choices=[('brocoli', 'Brocoli'), ('carotte', 'Carotte'), ('poivron', 'Poivron')], max_length=50)),
                ('accompagnement', models.CharField(choices=[('riz', 'Riz'), ('quinoa', 'Quinoa'), ('patate', 'Patate')], max_length=50)),
                ('cuisson', models.CharField(choices=[('grille', 'Grillé'), ('vapeur', 'Vapeur'), ('poele', 'Poêle')], max_length=50)),
                ('calories_calculees', models.IntegerField()),
                ('proteines_calculees', models.IntegerField()),
                ('prix_calcule', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.commande')),
                ('personnalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personnalisation')),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plat')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('regime', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_sombre', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
