# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='plats.dishcategory')),
            ],
            options={
                'verbose_name': 'Catégorie de plat',
                'verbose_name_plural': 'Catégories de plats',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='dishes/')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('calories_kcal', models.PositiveIntegerField(default=0)),
                ('protein_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('is_customizable', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('allergens', models.ManyToManyField(blank=True, related_name='dishes', to='allergies.allergen')),
                ('categories', models.ManyToManyField(blank=True, related_name='dishes', to='plats.dishcategory')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('calories_kcal_100g', models.PositiveIntegerField(default=0)),
                ('protein_g_100g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('carbs_g_100g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fat_g_100g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='ingredients', to='allergies.allergen')),
                ('compatible_diets', models.ManyToManyField(blank=True, related_name='ingredients_compatible', to='allergies.diettype')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_g', models.PositiveIntegerField(default=0)),
                ('is_optional', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_ingredients', to='plats.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_in_dishes', to='plats.ingredient')),
            ],
            options={
                'verbose_name': 'Ingrédient de plat',
                'verbose_name_plural': 'Ingrédients de plat',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', through='plats.DishIngredient', to='plats.ingredient'),
        ),
        migrations.AddIndex(
            model_name='dishcategory',
            index=models.Index(fields=['parent'], name='dishcat_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='dishcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='uniq_category_parent_slug'),
        ),
        migrations.AddConstraint(
            model_name='dishcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_category_parent_name'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['slug'], name='ingredient_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['is_active'], name='ingredient_active_idx'),
        ),
        migrations.AddIndex(
            model_name='dishingredient',
            index=models.Index(fields=['dish', 'sort_order'], name='dish_ing_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='dishingredient',
            constraint=models.UniqueConstraint(fields=('dish', 'ingredient'), name='uniq_dish_ingredient'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_available', 'is_customizable'], name='dish_flags_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['slug'], name='dish_slug_idx'),
        ),
    ]
