# Generated by Django 6.0.3 on 2026-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='dishcategory',
            index=models.Index(fields=['is_active'], name='dishcat_active_idx'),
        ),
    ]
