# Generated by Django 6.0.3 on 2026-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0003_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Temps de préparation en minutes'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='dishes/'),
        ),
    ]
