# Generated by Django 6.0.3 on 2026-04-03 10:21

import commandes.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(default=commandes.models.generate_order_number, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payée'), ('PREPARING', 'Préparée'), ('DELIVERED', 'Livrée'), ('CANCELED', 'Annulée'), ('REFUNDED', 'Remboursée')], default='PENDING', max_length=12)),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_type', models.CharField(choices=[('DELIVERY', 'Livraison'), ('PICKUP', 'À emporter'), ('COMPANY', 'Livraison entreprise')], default='DELIVERY', max_length=10)),
                ('requested_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_phone', models.CharField(blank=True, max_length=32)),
                ('addr_line1', models.CharField(blank=True, max_length=255)),
                ('addr_line2', models.CharField(blank=True, max_length=255)),
                ('addr_city', models.CharField(blank=True, max_length=120)),
                ('addr_region', models.CharField(blank=True, max_length=120)),
                ('addr_postal_code', models.CharField(blank=True, max_length=20)),
                ('addr_country_code', models.CharField(blank=True, max_length=2)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('item_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Évènement commande',
                'verbose_name_plural': 'Évènements commande',
            },
        ),
    ]
