# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
import django.utils.timezone
import entreprise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(default=entreprise.models.generate_company_invoice_number, editable=False, max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(blank=True, upload_to='company_invoices/')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='MAD', max_length=3)),
            ],
            options={
                'verbose_name': 'Facture entreprise',
                'verbose_name_plural': 'Factures entreprise',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('ADMIN', 'Admin'), ('MEMBER', 'Membre')], default='MEMBER', max_length=10)),
            ],
            options={
                'verbose_name': 'Membre entreprise',
                'verbose_name_plural': 'Membres entreprise',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_address', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'indexes': [models.Index(fields=['slug'], name='company_slug_idx'), models.Index(fields=['is_active'], name='company_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyGroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('LOCKED', 'Verrouillée'), ('SUBMITTED', 'Soumise'), ('DELIVERED', 'Livrée'), ('CANCELED', 'Annulée')], default='OPEN', max_length=10)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_window', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='entreprise.company')),
            ],
            options={
                'verbose_name': 'Commande groupée entreprise',
                'verbose_name_plural': 'Commandes groupées entreprise',
            },
        ),
    ]
