# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companygrouporder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_group_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='entreprise.company'),
        ),
        migrations.AddField(
            model_name='companyinvoice',
            name='group_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='entreprise.companygrouporder'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='entreprise.company'),
        ),
        migrations.AddField(
            model_name='companymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companygrouporder',
            index=models.Index(fields=['company', 'status', 'delivery_date'], name='grouporder_csd_idx'),
        ),
        migrations.AddIndex(
            model_name='companyinvoice',
            index=models.Index(fields=['issued_at'], name='companyinv_issued_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['company', 'role'], name='company_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymember',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_company_user'),
        ),
    ]
