# Generated by Django 6.0.3 on 2026-04-03 10:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnalisation', '0002_initial'),
        ('plats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation chatbot',
                'verbose_name_plural': 'Conversations chatbot',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('USER', 'user'), ('ASSISTANT', 'assistant'), ('SYSTEM', 'system'), ('TOOL', 'tool')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, upload_to='chat_audio/')),
                ('transcript', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation')),
            ],
            options={
                'verbose_name': 'Message chatbot',
                'verbose_name_plural': 'Messages chatbot',
            },
        ),
        migrations.CreateModel(
            name='ChatRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('custom_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personnalisation.customdish')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plats.dish')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='chatbot.chatmessage')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chatmsg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrecommendation',
            index=models.Index(fields=['message'], name='chatrec_message_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dish__isnull', False), ('custom_dish__isnull', True)), models.Q(('dish__isnull', True), ('custom_dish__isnull', False)), _connector='OR'), name='check_chatrec_xor_product'),
        ),
    ]
