# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDishComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Composant sélectionné',
                'verbose_name_plural': 'Composants sélectionnés',
            },
        ),
        migrations.CreateModel(
            name='DishCustomizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_select', models.PositiveSmallIntegerField(default=0)),
                ('max_select', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Règle de personnalisation',
                'verbose_name_plural': 'Règles de personnalisation',
            },
        ),
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PROTEIN', 'Protéine'), ('VEGETABLE', 'Légume'), ('SIDE', 'Accompagnement'), ('SAUCE', 'Sauce'), ('COOKING', 'Mode de cuisson')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Groupe de composants',
                'verbose_name_plural': 'Groupes de composants',
                'indexes': [models.Index(fields=['kind', 'is_active'], name='group_kind_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='uniq_group_kind_name')],
            },
        ),
        migrations.CreateModel(
            name='ComponentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('calories_kcal', models.PositiveIntegerField(default=0)),
                ('protein_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-1000.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))])),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='personnalisation.componentgroup')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plats.ingredient')),
            ],
            options={
                'verbose_name': 'Composant',
                'verbose_name_plural': 'Composants',
            },
        ),
        migrations.CreateModel(
            name='CustomDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('calories_kcal', models.PositiveIntegerField(default=0)),
                ('protein_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('nutrition_breakdown', models.JSONField(blank=True, default=dict)),
                ('base_dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_variants', to='plats.dish')),
            ],
            options={
                'verbose_name': 'Plat personnalisé',
                'verbose_name_plural': 'Plats personnalisés',
            },
        ),
    ]
