# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnalisation', '0001_initial'),
        ('plats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customdish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_dishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customdishcomponent',
            name='component_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_custom_dishes', to='personnalisation.componentitem'),
        ),
        migrations.AddField(
            model_name='customdishcomponent',
            name='custom_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='personnalisation.customdish'),
        ),
        migrations.AddField(
            model_name='dishcustomizationrule',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_rules', to='plats.dish'),
        ),
        migrations.AddField(
            model_name='dishcustomizationrule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_rules', to='personnalisation.componentgroup'),
        ),
        migrations.AddIndex(
            model_name='componentitem',
            index=models.Index(fields=['group', 'is_available'], name='component_group_avail_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentitem',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='uniq_component_group_name'),
        ),
        migrations.AddIndex(
            model_name='customdish',
            index=models.Index(fields=['user', 'created_at'], name='customdish_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='customdishcomponent',
            index=models.Index(fields=['custom_dish', 'sort_order'], name='customdish_comp_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='customdishcomponent',
            constraint=models.UniqueConstraint(fields=('custom_dish', 'component_item'), name='uniq_customdish_component'),
        ),
        migrations.AddConstraint(
            model_name='dishcustomizationrule',
            constraint=models.UniqueConstraint(fields=('dish', 'group'), name='uniq_dish_group_rule'),
        ),
        migrations.AddConstraint(
            model_name='dishcustomizationrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_select__lte', models.F('max_select'))), name='check_min_le_max'),
        ),
    ]
