# Generated by Django 6.0.3 on 2026-04-08 18:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnalisation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('proteins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))])),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Choix de composant',
                'verbose_name_plural': 'Choix de composants',
                'indexes': [models.Index(fields=['name', 'is_available'], name='componentchoice_name_avail_idx')],
            },
        ),
    ]
