# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strict_level', models.CharField(choices=[('PREFERENCE', 'Préférence'), ('STRICT', 'Strict'), ('MEDICAL', 'Médical')], default='PREFERENCE', max_length=12)),
            ],
            options={
                'verbose_name': 'Régime utilisateur',
                'verbose_name_plural': 'Régimes utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Allergène',
                'verbose_name_plural': 'Allergènes',
                'indexes': [models.Index(fields=['slug'], name='allergen_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Régime alimentaire',
                'verbose_name_plural': 'Régimes alimentaires',
                'indexes': [models.Index(fields=['slug'], name='diet_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('MILD', 'Légère'), ('MODERATE', 'Modérée'), ('SEVERE', 'Sévère')], default='MODERATE', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='allergies.allergen')),
            ],
            options={
                'verbose_name': 'Allergie utilisateur',
                'verbose_name_plural': 'Allergies utilisateur',
            },
        ),
    ]
