# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userallergy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='allergies.diettype'),
        ),
        migrations.AddField(
            model_name='userdiet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userallergy',
            index=models.Index(fields=['user', 'severity'], name='user_allergy_sev_idx'),
        ),
        migrations.AddConstraint(
            model_name='userallergy',
            constraint=models.UniqueConstraint(fields=('user', 'allergen'), name='uniq_user_allergen'),
        ),
        migrations.AddIndex(
            model_name='userdiet',
            index=models.Index(fields=['user', 'strict_level'], name='user_diet_level_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdiet',
            constraint=models.UniqueConstraint(fields=('user', 'diet'), name='uniq_user_diet'),
        ),
    ]
