# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnalisation', '0002_initial'),
        ('plats', '0001_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='custom_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnalisation.customdish'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plats.dish'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postshare',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='social.socialpost'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.socialpost'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.socialpost'),
        ),
        migrations.AddConstraint(
            model_name='challengeparticipation',
            constraint=models.UniqueConstraint(fields=('challenge', 'user'), name='uniq_challenge_user'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['created_at', 'visibility'], name='post_feed_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_dish__isnull', True), ('dish__isnull', True)), models.Q(('dish__isnull', False), ('custom_dish__isnull', True)), models.Q(('dish__isnull', True), ('custom_dish__isnull', False)), _connector='OR'), name='check_post_xor_dish_optional'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['post', 'created_at'], name='share_post_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_like_post_user'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post', 'created_at'], name='comment_post_created_idx'),
        ),
    ]
