# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie FAQ',
                'verbose_name_plural': 'Catégories FAQ',
                'indexes': [models.Index(fields=['slug'], name='faqcat_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='faq.faqcategory')),
            ],
            options={
                'verbose_name': 'Entrée FAQ',
                'verbose_name_plural': 'Entrées FAQ',
            },
        ),
        migrations.CreateModel(
            name='FAQFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('was_helpful', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='faq.faqentry')),
            ],
            options={
                'verbose_name': 'Feedback FAQ',
                'verbose_name_plural': 'Feedbacks FAQ',
            },
        ),
    ]
