# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faqfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='faqentry',
            index=models.Index(fields=['is_published', 'language'], name='faq_pub_lang_idx'),
        ),
        migrations.AddIndex(
            model_name='faqfeedback',
            index=models.Index(fields=['entry', 'created_at'], name='faqfb_entry_created_idx'),
        ),
    ]
