# Generated by Django 6.0.3 on 2026-04-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqentry',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
