# Generated by Django 6.0.3 on 2026-04-03 10:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import paiement.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(default=paiement.models.generate_invoice_number, editable=False, max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_address', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=40)),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='commandes.order')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'indexes': [models.Index(fields=['issued_at'], name='invoice_issued_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('CMI', 'CMI'), ('CASH', 'Paiement à la livraison')], max_length=12)),
                ('status', models.CharField(choices=[('CREATED', 'Créé'), ('REQUIRES_ACTION', 'Action requise'), ('SUCCEEDED', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELED', 'Annulé')], default='CREATED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intent', to='commandes.order')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'indexes': [models.Index(fields=['status', 'created_at'], name='pay_status_created_idx')],
            },
        ),
    ]
