# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_initial'),
        ('fidelite', '0001_initial'),
        ('plats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fidelite.loyaltyaccount'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commandes.order'),
        ),
        migrations.AddField(
            model_name='reward',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plats.dish'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='fidelite.loyaltyaccount'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commandes.order'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='fidelite.reward'),
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['points_balance'], name='loyalty_points_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['account', 'created_at'], name='loyalty_tx_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['reward_type', 'is_active'], name='reward_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('points_cost__gt', 0)), name='check_reward_cost_gt_0'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['account', 'created_at'], name='redeem_account_idx'),
        ),
    ]
